"""Render a converted + enriched rule into clean, reviewable Markdown.

The output is meant to drop straight into a detection-as-code repo or a PR
description: query first, then the LLM-generated context, then provenance.
"""

from __future__ import annotations

from datetime import datetime, timezone

from detection_forge.enricher import Enrichment
from detection_forge.sigma_loader import SigmaRule


def render_markdown(
    rule: SigmaRule,
    query: str,
    target: str,
    enrichment: Enrichment,
    ai_provider: str,
) -> str:
    """Return a Markdown document describing the detection."""
    lines: list[str] = []
    add = lines.append

    add(f"# {rule.title}")
    add("")
    if rule.description:
        add(f"> {rule.description}")
        add("")

    # --- metadata table ---
    add("| | |")
    add("|---|---|")
    add(f"| **Severity** | {rule.level} |")
    add(f"| **Status** | {rule.status} |")
    if rule.logsource:
        ls = ", ".join(f"{k}={v}" for k, v in rule.logsource.items())
        add(f"| **Log source** | {ls} |")
    if rule.rule_id:
        add(f"| **Sigma ID** | `{rule.rule_id}` |")
    if rule.author:
        add(f"| **Author** | {rule.author} |")
    add(f"| **Target** | {target} |")
    add("")

    # --- query ---
    add(f"## Detection query ({target})")
    add("")
    add("```kql")
    add(query.strip())
    add("```")
    add("")

    # --- enrichment ---
    if enrichment.parse_error:
        add("## AI enrichment")
        add("")
        add(f"> ⚠️ Enrichment unavailable: {enrichment.parse_error}")
        add("")
    else:
        if enrichment.summary:
            add("## Summary")
            add("")
            add(enrichment.summary)
            add("")

        if enrichment.attack:
            add("## MITRE ATT&CK")
            add("")
            add("| Technique | Name | Tactic |")
            add("|---|---|---|")
            for t in enrichment.attack:
                add(f"| `{t.id}` | {t.name} | {t.tactic} |")
            add("")

        if enrichment.severity_rationale:
            add("## Severity rationale")
            add("")
            add(enrichment.severity_rationale)
            add("")

        if enrichment.false_positives:
            add("## Known false positives")
            add("")
            for fp in enrichment.false_positives:
                add(f"- {fp}")
            add("")

        if enrichment.tuning:
            add("## Tuning suggestions")
            add("")
            for tip in enrichment.tuning:
                add(f"- {tip}")
            add("")

        if enrichment.investigation_steps:
            add("## Investigation steps")
            add("")
            for i, step in enumerate(enrichment.investigation_steps, 1):
                add(f"{i}. {step}")
            add("")

    # --- provenance ---
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    add("---")
    add(
        f"*Generated by DetectionForge on {stamp}. "
        f"Conversion: pySigma (deterministic). "
        f"Enrichment: {ai_provider}.*"
    )
    add("")

    return "\n".join(lines)
